import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, Info, Lock, MapPin, Package, Search } from 'lucide-react';

export interface AtlasRow { blueprint: string; map: string; condition: string; containers: string; notes: string; location: string; route: string; crafting: string; workshop: string; questReward: boolean; trialsReward: boolean; }
interface AtlasGroup { name: string; rows: AtlasRow[]; maps: string[]; containers: string[]; rarity: string; }
const MAPS = ['All', 'Dam Battlegrounds', 'Blue Gate', 'Buried City', 'Spaceport', 'Stella Montis'];
const CONDITIONS = ['All', 'Day', 'Night', 'Storm', 'Montis', 'Any', 'Bunker', 'Hurricane', 'Hidden Bunker'];
const RARITIES = ['All', 'common', 'uncommon', 'rare', 'very rare', 'legendary', 'epic'];

export function parseAtlasCsv(text: string): AtlasRow[] { const [, ...records] = parseCsv(text); return records.filter((record) => record[0]).map((record) => ({ blueprint: record[0].trim(), map: record[1]?.trim() || 'All', condition: record[2]?.trim() || 'Any', containers: record[4]?.trim() || '', questReward: record[5]?.trim().toLowerCase() === 'yes', trialsReward: record[6]?.trim().toLowerCase() === 'yes', notes: record[11]?.trim() || '', location: record[12]?.trim() || '', route: record[13]?.trim() || '', crafting: record[14]?.trim() || '', workshop: record[15]?.trim() || '' })); }

function parseCsv(text: string): string[][] { const rows: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false; for (let index = 0; index < text.length; index += 1) { const char = text[index]; if (quoted) { if (char === '"' && text[index + 1] === '"') { cell += '"'; index += 1; } else if (char === '"') quoted = false; else cell += char; } else if (char === '"') quoted = true; else if (char === ',') { row.push(cell); cell = ''; } else if (char === '\n') { row.push(cell.replace(/\r$/, '')); rows.push(row); row = []; cell = ''; } else cell += char; } if (row.length || cell) { row.push(cell); rows.push(row); } return rows; }
function atlasRarity(reports: number, maps: number): string { if (reports >= 100 && maps >= 5) return 'common'; if (reports >= 50 && maps >= 3) return 'uncommon'; if (reports >= 20) return 'rare'; if (reports >= 10) return 'very rare'; return 'legendary'; }
function locked(row: AtlasRow): boolean { const value = `${row.condition} ${row.notes}`.toLowerCase(); return value.includes('key room') || value.includes('breaching') || (value.includes('locked') && !value.includes("wasn't")); }

export function AtlasBlueprintPanel({ initialSearch = '' }: { initialSearch?: string }) {
  const [rows, setRows] = useState<AtlasRow[] | null>(null); const [error, setError] = useState(false); const [search, setSearch] = useState(''); const [mapFilter, setMapFilter] = useState('All'); const [rarityFilter, setRarityFilter] = useState('All'); const [conditionFilter, setConditionFilter] = useState('All'); const [expanded, setExpanded] = useState<Set<string>>(new Set());
  useEffect(() => { if (initialSearch) setSearch(initialSearch); }, [initialSearch]);
  useEffect(() => { fetch('/data/blueprints/atlas.csv').then((response) => { if (!response.ok) throw new Error(String(response.status)); return response.text(); }).then((text) => setRows(parseAtlasCsv(text))).catch(() => { setRows([]); setError(true); }); }, []);
  const grouped = useMemo<AtlasGroup[]>(() => { const groups = new Map<string, AtlasRow[]>(); (rows ?? []).forEach((row) => groups.set(row.blueprint, [...(groups.get(row.blueprint) ?? []), row])); return [...groups].map(([name, matches]) => { const maps = [...new Set(matches.map((row) => row.map).filter(Boolean))]; return { name, rows: matches, maps, containers: [...new Set(matches.map((row) => row.containers).filter(Boolean))], rarity: atlasRarity(matches.length, maps.length) }; }).sort((left, right) => right.rows.length - left.rows.length); }, [rows]);
  const filtered = useMemo(() => grouped.filter((blueprint) => (!search || blueprint.name.toLowerCase().includes(search.toLowerCase())) && (rarityFilter === 'All' || blueprint.rarity === rarityFilter) && (mapFilter === 'All' || blueprint.maps.includes(mapFilter))), [grouped, mapFilter, rarityFilter, search]);
  if (rows === null) return <div className="blueprints-empty">Loading Atlas Data…</div>;
  if (error) return <div className="blueprints-empty">Failed to load atlas data</div>;
  return <section className="atlas-panel"><div className="atlas-stats"><div><small>Total Entries</small><strong>{rows.length.toLocaleString()}</strong></div><div><small>Blueprints</small><strong>{grouped.length}</strong></div><div><small>Maps Covered</small><strong>{MAPS.length - 1}</strong></div><p><Info size={14} /><span><b>Rarity = community dataset heuristic</b>Common ≥100 reports + 5 maps · Uncommon ≥50 + 3 maps · Rare ≥20 · Very Rare ≥10 · Legendary &lt;10</span></p></div><div className="atlas-filters"><label><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search blueprint name..." /></label><select value={mapFilter} onChange={(event) => setMapFilter(event.target.value)}>{MAPS.map((value) => <option key={value}>{value}</option>)}</select><select value={conditionFilter} onChange={(event) => setConditionFilter(event.target.value)}>{CONDITIONS.map((value) => <option key={value}>{value}</option>)}</select><select value={rarityFilter} onChange={(event) => setRarityFilter(event.target.value)}>{RARITIES.map((value) => <option key={value}>{value}</option>)}</select></div><div className="atlas-list">{filtered.map((blueprint) => { const open = expanded.has(blueprint.name); const visibleRows = blueprint.rows.filter((row) => (mapFilter === 'All' || row.map === mapFilter) && (conditionFilter === 'All' || row.condition === conditionFilter)); return <article className={`atlas-entry atlas-entry--${blueprint.rarity.replace(' ', '-')}`} key={blueprint.name}><button className="atlas-entry__heading" onClick={() => setExpanded((current) => { const next = new Set(current); open ? next.delete(blueprint.name) : next.add(blueprint.name); return next; })}><div><strong>{blueprint.name}</strong><span>{blueprint.rarity}</span></div><div><span><MapPin size={14} />{blueprint.maps.length} maps</span><span><Package size={14} />{blueprint.rows.length} reports</span>{open ? <ChevronUp /> : <ChevronDown />}</div></button>{open && <div className="atlas-entry__rows">{visibleRows.map((row, index) => <div className="atlas-row" key={`${blueprint.name}-${index}`}><header><MapPin size={14} /><strong>{row.map}</strong><span>{row.condition}</span>{locked(row) && <Lock size={14} />}</header>{row.containers && <p><b>Containers:</b> {row.containers}</p>}{row.location && <p><b>Location:</b> {row.location}</p>}{row.route && <p><b>Best Route:</b> {row.route}</p>}{row.crafting && <p><b>Crafting:</b> {row.crafting}{row.workshop ? ` · ${row.workshop}` : ''}</p>}{row.notes && <p><b>Notes:</b> {row.notes}</p>}</div>)}</div>}</article>; })}</div></section>;
}
